name: massai mara park 01 docker ec2

on:
  workflow_dispatch

env:
  DOCKER_USERNAME: siestageek
  IMAGE_NAME: massai_mara
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  build_image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:v${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: docker operations
        run: |
          docker image ls

      - name: Save Docker image
        run: |
          docker save ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:v${{ env.IMAGE_TAG }} > image.tar
      
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar
          # retention-days: 1

  hub_push:
    needs: build_image
    runs-on: ubuntu-22.04

    steps:
      - name: download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: check downloaded files
        run: ls -al   

      - name: Load Docker image
        run: |
          docker load < image.tar        

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker operations
        run: |         
          docker push  ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:v${{ env.IMAGE_TAG }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:v${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker search ${{ env.IMAGE_NAME }}:latest

      - name: logout from docker hub
        if: always()
        run: docker logout

  upload_compose:
    needs: hub_push
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_USER_NAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 12137
          source: "compose-multijobs.yaml"
          target: "/home/${{ secrets.EC2_USER_NAME }}"
          strip_components: 1
  

  ec2_run_test:
    needs: upload_compose
    name: Test EC2 SSH Connection
    runs-on: ubuntu-22.04

    steps:      
      # SSH로 EC2에 접속하여 배포 스크립트 실행
      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_USER_NAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 12137
          script: |
            docker compose -f ./compose-multijobs.yaml up -d  
            sleep 30
          
            docker compose ps
            docker compose logs
       
